from __future__ import annotations

import json
import math
from pathlib import Path
from typing import Any

from app.config import resource_path

LEVELS = ("healthy", "minimal", "minor", "warning", "poor", "bad", "critical")
DEFAULT_BANDS: list[dict[str, Any]] = [
    {"max": 0, "level": "healthy", "color": "#3bc878", "opacity": 0.18, "radius": 84, "blur": 0, "vivid": True},
    {"max": 1, "level": "minimal", "color": "#3bc878", "opacity": 0.14, "radius": 80, "blur": 0, "vivid": True},
    {"max": 3, "level": "minor", "color": "#b5d446", "opacity": 0.24, "radius": 82, "blur": 18, "vivid": False},
    {"max": 7, "level": "warning", "color": "#f2be3f", "opacity": 0.52, "radius": 96, "blur": 16, "vivid": False},
    {"max": 15, "level": "poor", "color": "#f47b3f", "opacity": 0.36, "radius": 98, "blur": 28, "vivid": False},
    {"max": 30, "level": "bad", "color": "#ee4758", "opacity": 0.44, "radius": 106, "blur": 30, "vivid": False},
    {"max": None, "level": "critical", "color": "#c80f24", "opacity": 0.52, "radius": 114, "blur": 34, "vivid": False},
]


class HeatmapBandsError(ValueError):
    """Raised when heatmap band configuration is invalid."""


def json_path() -> Path:
    return resource_path("app", "static", "heatmap-bands.json")


def js_path() -> Path:
    return resource_path("app", "static", "heatmap-bands.js")


def _normalize_band(raw: dict[str, Any], *, last: bool) -> dict[str, Any]:
    level = raw.get("level")
    if level not in LEVELS:
        raise HeatmapBandsError(f"Unknown heatmap level {level!r}.")
    color = raw.get("color")
    if not isinstance(color, str) or not color.startswith("#") or len(color) not in {4, 7}:
        raise HeatmapBandsError(f"Heatmap color for {level} is invalid.")
    opacity = raw.get("opacity")
    radius = raw.get("radius")
    blur = raw.get("blur")
    vivid = raw.get("vivid")
    if isinstance(opacity, bool) or not isinstance(opacity, (int, float)) or not 0 <= float(opacity) <= 1:
        raise HeatmapBandsError(f"Opacity for {level} must be between 0 and 1.")
    if isinstance(radius, bool) or not isinstance(radius, (int, float)) or not 20 <= float(radius) <= 180:
        raise HeatmapBandsError(f"Radius for {level} must be between 20 and 180.")
    if isinstance(blur, bool) or not isinstance(blur, (int, float)) or not 0 <= float(blur) <= 60:
        raise HeatmapBandsError(f"Blur for {level} must be between 0 and 60.")
    if not isinstance(vivid, bool):
        raise HeatmapBandsError(f"Vivid flag for {level} must be boolean.")
    if last:
        maximum: float | None = None
    else:
        maximum_raw = raw.get("max")
        if isinstance(maximum_raw, bool) or not isinstance(maximum_raw, (int, float)):
            raise HeatmapBandsError(f"Max loss for {level} must be a number.")
        maximum = float(maximum_raw)
        if not math.isfinite(maximum) or maximum < 0:
            raise HeatmapBandsError(f"Max loss for {level} must be a non-negative number.")
    return {
        "max": maximum,
        "level": level,
        "color": color,
        "opacity": round(float(opacity), 3),
        "radius": round(float(radius), 1),
        "blur": round(float(blur), 1),
        "vivid": vivid,
    }


def validate_bands(raw: object) -> list[dict[str, Any]]:
    if not isinstance(raw, list) or len(raw) != len(LEVELS):
        raise HeatmapBandsError("Heatmap bands must be a list with one entry per severity level.")
    normalized = [
        _normalize_band(item, last=index == len(LEVELS) - 1)
        for index, item in enumerate(raw)
    ]
    if [band["level"] for band in normalized] != list(LEVELS):
        raise HeatmapBandsError("Heatmap bands must appear in the standard severity order.")
    maxima = [band["max"] for band in normalized[:-1]]
    if any(left >= right for left, right in zip(maxima, maxima[1:], strict=False)):
        raise HeatmapBandsError("Heatmap max loss thresholds must strictly increase.")
    return normalized


def load_bands() -> list[dict[str, Any]]:
    path = json_path()
    if not path.is_file():
        save_bands(DEFAULT_BANDS)
        return validate_bands(DEFAULT_BANDS)
    try:
        document = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as error:
        raise HeatmapBandsError("Heatmap band configuration could not be read.") from error
    return validate_bands(document)


def _js_payload(bands: list[dict[str, Any]]) -> str:
    script_bands = []
    for band in bands:
        entry = {**band}
        if entry["max"] is None:
            entry["max"] = float("inf")
        script_bands.append(entry)
    encoded = json.dumps(script_bands, indent=2)
    return (
        "/* Generated by Status Visualizer dev tools; edit via /dev/heatmap */\n"
        f"globalThis.__HEATMAP_LOSS_BANDS = Object.freeze({encoded});\n"
    )


def save_bands(raw: object) -> list[dict[str, Any]]:
    bands = validate_bands(raw)
    json_ready = []
    for band in bands:
        entry = {**band}
        if entry["max"] is None:
            entry["max"] = None
        json_ready.append(entry)
    json_path().write_text(json.dumps(json_ready, indent=2) + "\n", encoding="utf-8")
    js_path().write_text(_js_payload(bands), encoding="utf-8")
    return bands


def ensure_generated_files() -> None:
    if json_path().is_file() and js_path().is_file():
        return
    save_bands(DEFAULT_BANDS)
